import Head from 'next/head'
import Table from '../components/Table'
import { useMemo } from 'react'
import { getContent } from './api/videos'

export default function Home({ lastUpdated, videos }) {

  const data = useMemo(() => videos, [])
  const columns = useMemo(() => [
    {
      Header: "Published At",
      accessor: (row) => {
        return <div className='text-left'>{(new Date(row.publishedAt)).toDateString()}</div>
      },
    },
    {
      Header: "Title",
      accessor: (row) => {
        return <div className='break-normal text-left'>{row.title}</div>
      },
    },
    {
      Header: "Views",
      accessor: "viewCount"
    },
    {
      Header: 'Thumbnail',
      accessor: (row) => {
        return <img src={row.thumbnails.default.url}/>
      },
    },
    {
      Header: 'View',
      accessor: (row) => {
        return <a href={`https://youtu.be/${row.id}`}>👀</a>
      },
    }
  ], [])

  return (
    <div className='bg-black '>
      <Head>
        <title>Hi 👋, my name is Fernando Palacios</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='text-center py-8'>
        <h1 className='text-white text-4xl font-semibold'>
        Hi 👋, my name is <a href='https://bio.link/fernandops26' className='text-blue-700 text-bold hover:underline'>Fernando Palacios</a>
        </h1>

        <p className='text-white mt-8 text-2xl font-medium'>
          These are my recents videos on my <a className='text-red-700 hover:underline' href="https://www.youtube.com/c/FernandoPalacios26">Youtube channel</a>
        </p>

        <p className='text-white py-4 font-semibold text-gray-300'>Updated to {(new Date(lastUpdated)).toLocaleString()} using a cron job</p>

        <div className='flex flex-col'>
          <div className='align-middle inline-block'>
            <div className='shadow overflow-hidden border-b border-gray-200 sm:rounded-lg max-w-6xl overflow-x-auto m-auto'>
                <Table data={data} columns={columns} />
            </div>
          </div>
        </div>
      </main>
    </div>
  )
}

export async function getStaticProps(context) {
  const content = getContent()

  if (!content) {
    return {
      notFound: true,
    }
  }

  return {
    props: {
      lastUpdated: content.lastUpdated,
      videos: content.videos
    },
    revalidate: 60
  }
}
